services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports: 
      - '8000:8000'
    depends_on: 
      - mongo 
      - redis
    networks:
      - internal
  mongo:
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    networks:
      - internal

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - internal
      - default
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: passpass
    ports:
      - 8081:8081
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

networks:
  internal:

volumes:
  data:
  redis_data:
