name: TestAction
on:
  push:
    branches:
      - main

jobs:
  build:
    name: TestAction
    runs-on: ubuntu-latest
    steps:
      - name: TestAction
        run: echo "What's Up Phil"

      - name: Create env file
        run: |
          echo "APP_MODE=${{ secrets.APP_MODE }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "REFRESH_TOKEN_TTL=${{ secrets.REFRESH_TOKEN_TTL }}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
          echo "ACCESS_TOKEN_TTL=${{ secrets.ACCESS_TOKEN_TTL }}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "PROD_MONGO_URI=${{ secrets.PROD_MONGO_URI }}" >> .env
          echo "VAPID_SECRET_KEY=${{ secrets.VAPID_SECRET_KEY }}" >> .env
          echo "VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}" >> .env
          cat .env
    
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd zero-app-backend
            sudo bash deploy.sh

